<?php

$database = array(
  "movies" => array(
    array(
      "Nom" => "Forrest Gump",
      "Annee" => 1994,
      "Durée" => "2h20min",
      "Réalisateur" => "Robert Zemeckis",
      "Acteurs" => array("Tom Hanks", "Gary Siniseplus"),
      "Genres" => array("Comédie dramatique" , "Romance"),
      "Like" => 100806
    ),
    array(
      "Nom" => "Django Unchained",
      "Annee" => 2013,
      "Durée" => "2h44min",
      "Réalisateur" => "Quentin Tarantino",
      "Acteurs" => array("Jamie Foxx", "Christoph Waltz"),
      "Genres" => array("Western"),
      "Like" => 10030,
    ),
    array(
      "Nom" => "La Ligne verte",
      "Annee" => 2000,
      "Durée" => "3h9min",
      "Réalisateur" => "Frank Darabont",
      "Acteurs" => array("Tom Hanks", "Michael Clarke Duncan"),
      "Genres" => array("Fantastique" , "Policier"),
      "Like" => 20030,
    ),
    array(
      "Nom" => "Gran Torino",
      "Annee" => 2009,
      "Durée" => "1h51min",
      "Réalisateur" => "Clint Eastwood",
      "Acteurs" => array("Clint Eastwood", "Bee Vangplus"),
      "Genres" => array("Drame" , "Thriller"),
      "Like" => 1030,
    ),
    array(
      "Nom" => "La Liste de Schindler",
      "Annee" => 1994,
      "Durée" => "3h15min",
      "Réalisateur" => "Steven Spielberg",
      "Acteurs" => array("Liam Neeson", "Ben Kingsleyplus"),
      "Genres" => array("Historique", "Drame"),
      "Like" => 60070,
    ),
    array(
      "Nom" => "The Dark Knight, Le Chevalier Noir",
      "Annee" => 2008,
      "Durée" => "2h27min",
      "Réalisateur" => "Christopher Nolan",
      "Acteurs" => array("Christian Bale", "Heath Ledger"),
      "Genres" => array("Action" , "Drame"),
      "Like" => 89030,
    ),
    array(
      "Nom" => "Le Parrain",
      "Annee" => 1972,
      "Durée" => "2h55min",
      "Réalisateur" => "Francis Ford Coppola",
      "Acteurs" => array("Marlon Brando", "Al Pacino"),
      "Genres" => array("Policier" , "Drame"),
      "Like" => 60180,
    ),
    array(
      "Nom" => "Pulp Fiction",
      "Annee" => 1994,
      "Durée" => "2h29min",
      "Réalisateur" => "Quentin Tarantino",
      "Acteurs" => array("John Travolta", "Samuel L. Jackson"),
      "Genres" => array("Policier" , "Thriller"),
      "Like" => 40078,
    ),
    array(
      "Nom" => "Le Seigneur des anneaux : le retour du roi",
      "Annee" => 2003,
      "Durée" => "3h20min",
      "Réalisateur" => "Peter Jackson",
      "Acteurs" => array("Elijah Wood", "Sean Astin"),
      "Genres" => array("Fantastique" , "Aventure"),
      "Like" => 80050,
    ),
    array(
      "Nom" => "Fight Club",
      "Annee" => 1999,
      "Durée" => "2h15min",
      "Réalisateur" => "David Fincher",
      "Acteurs" => array("Brad Pitt", "Edward Norton"),
      "Genres" => array("Thriller" , "Drame"),
      "Like" => 8010,
    ),
    array(
      "Nom" => "Intouchables",
      "Annee" => 2011,
      "Durée" => "1h52min",
      "Réalisateur" => "Eric Toledano",
      "Acteurs" => array("François Cluzet", "Omar Sy"),
      "Genres" => array("Comédie"),
      "Like" => 89010,
    ),
    array(
      "Nom" => "Mommy",
      "Annee" => 2014,
      "Durée" => "2h18min",
      "Réalisateur" => "Xavier Dolan",
      "Acteurs" => array("Viviane Pascal", "Antoine-Olivier "),
      "Genres" => array("Drame"),
      "Like" => 59070,
    )
  ),
  "series" => array(
    array(
      "Nom" => "Secrets And Lies (US)",
      "Annee" => 2015,
      "Acteurs" => array("Juliette Lewis", "Michael Ealy"),
      "Genres" => array("Drame"),
      "Like" => 114,
    ),
    array(
      "Nom" => "The Walking Dead",
      "Annee" => 2010,
      "Acteurs" => array("Andrew Lincoln", "Steven Yeun"),
      "Genres" => array("Drame" , "Epouvante-horreur"),
      "Like" => 25708,
    ),
    array(
      "Nom" => "Game of Thrones",
      "Annee" => 2011,
      "Acteurs" => array("Peter Dinklage", "Nikolaj Coster-Waldau"),
      "Genres" => array("Drame" , "Fantastique"),
      "Like" => 31435,
    ),
    array(
      "Nom" => "Arrow",
      "Annee" => 2012,
      "Acteurs" => array("Stephen Amell", "Katie Cassidy"),
      "Genres" => array("Drame" , "Fantastique"),
      "Like" => 12087,
    ),
    array(
      "Nom" => "American Horror Story",
      "Annee" => 2011,
      "Acteurs" => array("Lady Gaga", "Kathy Bates"),
      "Genres" => array("Drame" , "Epouvante-horreur"),
      "Like" => 5181,
    ),
    array(
      "Nom" => "Les 100",
      "Annee" => 2014,
      "Acteurs" => array("Eliza Taylor", "Paige Turco"),
      "Genres" => array("Aventure" , "Drame"),
      "Like" => 5499,
    ),

    array(
      "Nom" => "Mr. Robot",
      "Annee" => 2014,
      "Acteurs" => array("Rami Malek", "Carly Chaikin"),
      "Genres" => array("Drame" , "Thriller"),
      "Like" => 1086,
    ),
    array(
      "Nom" => "Le Passager",
      "Annee" => 2014,
      "Acteurs" => array("Jean-Hugues Anglade", "Raphaëlle Agogué"),
      "Genres" => array("Thriller"),
      "Like" => 11,
    ),

    array(
      "Nom" => "Versailles",
      "Annee" => 2014,
      "Acteurs" => array("George Blagden", "Alexander Vlahos"),
      "Genres" => array("Drame" , "Historique"),
      "Like" => 59,
    ),
    array(
      "Nom" => "Profilage",
      "Annee" => 2014,
      "Acteurs" => array("Odile Vuillemin", "Philippe Bas"),
      "Genres" => array("Policier"),
      "Like" => 801,
    ),
    array(
      "Nom" => "Panthers / The Last Panthers",
      "Annee" => 2015,
      "Acteurs" => array("Samantha Morton", "Tahar Rahim"),
      "Genres" => array("Thriller"),
      "Like" => 28,
    ),
    array(
      "Nom" => "Vikings",
      "Annee" => 2013,
      "Acteurs" => array("Travis Fimmel", "Katheryn Winnick"),
      "Genres" => array("Aventure", "Drame"),
      "Like" => 63745,
    ),
  )
);